name: Workflow Liés

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Message job1
        run: echo "Job 1 exécuté manuellement"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Message job2
        run: echo "Job 2 exécuté après Job 1"
